import { ArrowRight, Check, ChevronDown, ChevronRight, Factory, Gem, Menu, MessageCircle, Ruler, ShieldCheck, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import type { FormEvent } from 'react';
import { Link, NavLink, Route, Routes, useLocation, useParams } from 'react-router-dom';
import { api } from './api';
import type { Category, Product } from './types';
import { Admin } from './Admin';
import { makeWhatsAppUrl } from './whatsapp';
import brandLogo from './assets/imagens/logo-altar-pulpitos.png';
import pulpitoCobreImage from './assets/imagens/pulpito-cobre-igreja.png';
import pulpitoDouradoImage from './assets/imagens/pulpito-dourado-igreja.png';
import pulpitoDuploPrataImage from './assets/imagens/pulpito-duplo-prata-igreja.png';
import pulpitoPrataImage from './assets/imagens/pulpito-prata-igreja.png';
import pulpitoTriploPrataImage from './assets/imagens/pulpito-triplo-prata-igreja.png';
import pulpitoPretoImage from './assets/imagens/pulpito-preto-igreja.png';
import pulpitoTriploMarromImage from './assets/imagens/pulpito-triplo-marrom-igreja.png';

const whatsapp = import.meta.env.VITE_WHATSAPP_NUMBER ?? '5562981200649';
const pulpitosCategory: Category = { id: 'pulpitos', name: 'Púlpitos', slug: 'pulpitos' };
const makeProduct = (name: string, slug: string, description: string, dimensions: string, image: string, sortOrder: number): Product => ({ id: slug, name, slug, description, dimensions, isPublished: true, sortOrder, categoryId: 'pulpitos', category: pulpitosCategory, images: [{ id: `${slug}-igreja`, url: image, alt: `${name} instalado em ambiente de igreja`, sortOrder: 0 }] });
const catalogFallback: Product[] = [
  makeProduct('Púlpito Cobre', 'pulpito-cobre', 'Púlpito para igreja com acabamento cobre, tampo de vidro e mesa lateral coordenada.', 'Medidas sob consulta', pulpitoCobreImage, 1),
  makeProduct('Púlpito Dourado', 'pulpito-dourado', 'Púlpito para igreja com acabamento dourado, tampo de vidro e mesa lateral coordenada.', 'Medidas sob consulta', pulpitoDouradoImage, 2),
  makeProduct('Púlpito Duplo Prata', 'pulpito-duplo-prata', 'Púlpito para igreja com duas colunas, acabamento prata e suporte integrado para copo ou microfone.', '115 × 70 × 40 cm', pulpitoDuploPrataImage, 3),
  makeProduct('Púlpito Prata', 'pulpito-prata', 'Púlpito para igreja em acabamento prata, com tampo de vidro e mesa lateral circular.', 'Púlpito: 115 × 70 × 40 cm · Mesa: 72 cm de altura e tampo de 45 cm', pulpitoPrataImage, 4),
  makeProduct('Púlpito Triplo Prata', 'pulpito-triplo-prata', 'Púlpito para igreja de três colunas, em acabamento prata e com mesa lateral coordenada.', 'Medidas sob consulta', pulpitoTriploPrataImage, 5),
  makeProduct('Púlpito Preto', 'pulpito-preto', 'Púlpito para igreja em acabamento preto, com vidro fumê e mesa lateral.', 'Medidas sob consulta', pulpitoPretoImage, 6),
  makeProduct('Púlpito Triplo Marrom', 'pulpito-triplo-marrom', 'Púlpito para igreja de três colunas, em acabamento marrom e com mesa lateral coordenada.', 'Medidas sob consulta', pulpitoTriploMarromImage, 7),
];

function usePageMeta(title: string, description: string) {
  useEffect(() => {
    document.title = title;
    document.querySelector('meta[name="description"]')?.setAttribute('content', description);
  }, [description, title]);
}

function Header() { const [open, setOpen] = useState(false); return <header className="header"><Link to="/" className="brand" aria-label="Altar Púlpitos, página inicial"><img src={brandLogo} alt="Altar Púlpitos"/></Link><button className="menu-button" onClick={() => setOpen(!open)} aria-label={open ? 'Fechar menu' : 'Abrir menu'}>{open ? <X /> : <Menu />}</button><nav className={open ? 'nav open' : 'nav'} onClick={() => setOpen(false)}><NavLink to="/catalogo">Púlpitos</NavLink><NavLink to="/sobre">A fábrica</NavLink><NavLink to="/contato">Contato</NavLink><Link className="button button-small" to="/catalogo">Pedir orçamento</Link></nav></header> }
function Footer() { return <footer><div><img className="footer-logo" src={brandLogo} alt="Altar Púlpitos"/><p>Púlpitos para igrejas, direto da fábrica e com envio para todo o Brasil.</p></div><div><strong>Atendimento</strong><p>Segunda a sexta, 8h às 18h</p></div><p>© {new Date().getFullYear()} Altar Púlpitos · Desenvolvido por <a href="https://evoluxx-olive.vercel.app" target="_blank" rel="noreferrer">Evolux</a></p></footer> }
function Layout({ children }: { children: React.ReactNode }) {
  const { pathname } = useLocation();
  useEffect(() => {
    const targets = Array.from(document.querySelectorAll<HTMLElement>('main > section, footer'));
    const reducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    if (reducedMotion) { targets.forEach(target => target.classList.add('is-visible')); return; }
    targets.forEach((target, index) => { target.classList.add('reveal'); target.style.setProperty('--reveal-delay', `${Math.min(index * 45, 180)}ms`); });
    const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) { entry.target.classList.add('is-visible'); observer.unobserve(entry.target); } }), { threshold: 0.12, rootMargin: '0px 0px -48px' });
    targets.forEach(target => observer.observe(target));
    return () => observer.disconnect();
  }, [pathname]);
  return <><Header/><main>{children}</main><Footer/><a className="whatsapp-float" href={`https://wa.me/${whatsapp}`} target="_blank" rel="noreferrer" aria-label="Falar com a Altar Púlpitos pelo WhatsApp"><MessageCircle size={28}/><span>WhatsApp</span></a></>
}
function ProductImage({ product }: { product: Product }) { return product.images[0] ? <img src={product.images[0].url} alt={product.images[0].alt || product.name} loading="lazy"/> : <div className="product-placeholder" aria-label={`Imagem indisponível de ${product.name}`}><span>AP</span></div> }
function Home() { const [products, setProducts] = useState<Product[]>([]); usePageMeta('Púlpitos para Igreja Direto da Fábrica | Altar Púlpitos', 'Conheça púlpitos para igreja direto da fábrica. Veja os modelos da Altar Púlpitos e solicite seu orçamento pelo WhatsApp. Enviamos para todo o Brasil.'); useEffect(() => { api.products().then(items => setProducts(items.length ? items : catalogFallback)).catch(() => setProducts(catalogFallback)); }, []); return <Layout>
  <section className="hero hero-new"><div className="hero-copy"><p className="eyebrow">PÚLPITOS PARA IGREJA, DIRETO DA FÁBRICA</p><h1>Púlpitos que valorizam a mensagem e o seu altar.</h1><p className="lead">Encontre um púlpito para igreja que una presença, funcionalidade e beleza. Escolha seu modelo e fale diretamente com quem fabrica.</p><div className="hero-actions"><Link className="button" to="/catalogo">Ver modelos <ArrowRight size={18}/></Link><a className="button button-outline" href={`https://wa.me/${whatsapp}`} target="_blank" rel="noreferrer"><MessageCircle size={18}/> Falar pelo WhatsApp</a></div><div className="hero-badges"><span><Check size={16}/> Fabricação própria</span><span><Check size={16}/> Envio para todo o Brasil</span></div></div><div className="hero-brand-card"><img src={pulpitoTriploMarromImage} alt="Púlpito Triplo Marrom em ambiente de igreja"/><div className="brand-card-line"/><p>Feito para<br/><strong>servir com excelência.</strong></p></div></section>
  <section className="trust-bar" aria-label="Diferenciais da Altar Púlpitos"><div className="marquee-track"><div className="marquee-group"><strong>Qualidade de fábrica</strong><span>•</span><strong>Atendimento próximo</strong><span>•</span><strong>Acabamento refinado</strong><span>•</span><strong>Direto da fábrica</strong><span>•</span><strong>Envio para todo o Brasil</strong><span>•</span><strong>Projetos para sua igreja</strong><span>•</span></div><div className="marquee-group" aria-hidden="true"><strong>Qualidade de fábrica</strong><span>•</span><strong>Atendimento próximo</strong><span>•</span><strong>Acabamento refinado</strong><span>•</span><strong>Direto da fábrica</strong><span>•</span><strong>Envio para todo o Brasil</strong><span>•</span><strong>Projetos para sua igreja</strong><span>•</span></div></div></section>
  <section className="section benefits"><div className="section-intro"><p className="eyebrow">FEITO PARA A SUA IGREJA</p><h2>Mais do que um púlpito: um apoio para a sua mensagem.</h2></div><div className="benefit-grid"><article><Factory size={30}/><h3>Direto da fábrica para o altar</h3><p>Você fala com uma equipe que conhece cada etapa da produção do seu púlpito.</p></article><article><Gem size={30}/><h3>Cuidado em cada detalhe</h3><p>Modelos pensados para compor o altar com beleza, equilíbrio e presença.</p></article><article><ShieldCheck size={30}/><h3>Atendimento claro do início ao fim</h3><p>Receba orientação para escolher o modelo e combinar a entrega para sua cidade.</p></article></div></section>
  <section className="catalog-preview"><div className="section section-heading-block"><p className="eyebrow">MODELOS DE PÚLPITOS PARA IGREJA</p><h2>Encontre o modelo ideal para o seu altar.</h2><p>Conheça opções para diferentes estilos de igreja e solicite um orçamento sem compromisso.</p><Link className="text-link" to="/catalogo">Explorar todos os modelos <ArrowRight size={18}/></Link></div><div className="section"><ProductGrid products={products.slice(0, 6)}/></div></section>
  <section className="process section"><div className="process-copy"><p className="eyebrow">COMO PEDIR SEU ORÇAMENTO</p><h2>Seu púlpito em 3 passos simples.</h2><p>Um atendimento direto e transparente para sua igreja escolher com segurança.</p><Link className="button" to="/contato">Solicitar orçamento <ArrowRight size={18}/></Link></div><ol><li><b>01</b><div><h3>Escolha um modelo</h3><p>Veja o catálogo e encontre o púlpito que mais combina com o seu espaço.</p></div></li><li><b>02</b><div><h3>Fale conosco pelo WhatsApp</h3><p>Informe o modelo desejado, seu nome e sua cidade.</p></div></li><li><b>03</b><div><h3>Combine a entrega</h3><p>Nossa equipe orienta você sobre as opções de envio para a sua região.</p></div></li></ol></section>
  <section className="testimony"><div className="quote-mark">“</div><blockquote>Nosso propósito é entregar um púlpito à altura da importância do altar e da mensagem compartilhada nele.</blockquote><p>Altar Púlpitos <span>•</span> Direto da fábrica</p></section>
  <section className="section faq"><div><p className="eyebrow">DÚVIDAS FREQUENTES</p><h2>O que você precisa saber antes de pedir seu orçamento</h2><p>Se precisar de ajuda para escolher, nossa equipe está pronta para atender pelo WhatsApp.</p></div><div className="faq-list"><details open><summary>Vocês enviam púlpitos para todo o Brasil?<ChevronDown size={18}/></summary><p>Sim. Informe sua cidade no atendimento para confirmarmos as opções de envio para a sua região.</p></details><details><summary>Como solicito um orçamento de púlpito?<ChevronDown size={18}/></summary><p>Escolha um modelo no catálogo, informe seu nome e cidade e você seguirá para o WhatsApp com uma mensagem pronta.</p></details><details><summary>Posso tirar dúvidas antes de escolher um modelo?<ChevronDown size={18}/></summary><p>Sim. Fale conosco pelo WhatsApp para receber orientação sobre os modelos e a entrega.</p></details></div></section>
  <section className="final-cta"><div><p className="eyebrow">ENCONTRE O PÚLPITO IDEAL</p><h2>Leve mais presença e organização para o seu altar.</h2><p>Veja os modelos disponíveis ou fale agora com a equipe da Altar Púlpitos.</p><div className="hero-actions"><Link className="button" to="/catalogo">Conhecer púlpitos <ArrowRight size={18}/></Link><a className="button button-outline-light" href={`https://wa.me/${whatsapp}`} target="_blank" rel="noreferrer">Chamar no WhatsApp</a></div></div></section>
</Layout> }
function ProductGrid({ products }: { products: Product[] }) { if (!products.length) return <p className="empty">O catálogo está sendo preparado. Volte em breve.</p>; return <div className="product-grid">{products.map(product => <article className="product-card" key={product.id}><Link to={`/catalogo/${product.slug}`}><ProductImage product={product}/><div><p>{product.category.name}</p><h3>{product.name}</h3><span>Ver detalhes <ArrowRight size={16}/></span></div></Link></article>)}</div> }
function Catalog() { const [products, setProducts] = useState<Product[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [active, setActive] = useState(''); usePageMeta('Catálogo de Púlpitos para Igreja | Altar Púlpitos', 'Explore o catálogo de púlpitos para igreja da Altar Púlpitos. Escolha seu modelo e solicite orçamento direto da fábrica pelo WhatsApp.'); useEffect(() => { api.categories().then(items => setCategories(items.length ? items : [pulpitosCategory])).catch(() => setCategories([pulpitosCategory])); }, []); useEffect(() => { api.products(active || undefined).then(items => setProducts(items.length ? items : catalogFallback)).catch(() => setProducts(catalogFallback)); }, [active]); return <Layout><section className="page-hero"><p className="eyebrow">CATÁLOGO DE PÚLPITOS PARA IGREJA</p><h1>Encontre o púlpito ideal para o seu altar.</h1><p>Conheça os modelos disponíveis, veja as medidas e solicite seu orçamento direto com a fábrica.</p></section><section className="section catalog"><div className="filters"><button className={!active ? 'active' : ''} onClick={() => setActive('')}>Todos</button>{categories.map(category => <button className={active === category.slug ? 'active' : ''} onClick={() => setActive(category.slug)} key={category.id}>{category.name}</button>)}</div><ProductGrid products={products}/></section></Layout> }
function ProductDetail() { const { slug = '' } = useParams(); const [product, setProduct] = useState<Product | null>(null); const [error, setError] = useState(''); usePageMeta(product ? `${product.name} para Igreja | Altar Púlpitos` : 'Púlpito para Igreja | Altar Púlpitos', product ? `Conheça o ${product.name}, um púlpito para igreja direto da fábrica. Veja as medidas e solicite seu orçamento pelo WhatsApp.` : 'Conheça os púlpitos para igreja da Altar Púlpitos e solicite seu orçamento direto da fábrica.'); useEffect(() => { api.product(slug).then(setProduct).catch(() => { const fallback = catalogFallback.find(item => item.slug === slug); if (fallback) setProduct(fallback); else setError('Produto não encontrado.'); }); }, [slug]); if (error) return <Layout><section className="section"><h1>{error}</h1><Link to="/catalogo">Voltar ao catálogo</Link></section></Layout>; if (!product) return <Layout><section className="section">Carregando produto…</section></Layout>; return <Layout><section className="detail section"><div className="detail-image"><ProductImage product={product}/></div><div><Link className="back" to="/catalogo">← Voltar ao catálogo</Link><p className="eyebrow">{product.category.name}</p><h1>{product.name}</h1><p className="detail-description">{product.description}</p><p className="dimensions"><Ruler size={18}/><strong>Medidas:</strong> {product.dimensions}</p><QuoteForm product={product.name}/></div></section></Layout> }
function QuoteForm({ product }: { product: string }) { const [name, setName] = useState(''); const [city, setCity] = useState(''); const submit = (event: FormEvent) => { event.preventDefault(); window.open(makeWhatsAppUrl(product, name, city), '_blank', 'noopener,noreferrer'); }; return <form className="quote-form" onSubmit={submit}><h2>Peça seu orçamento</h2><p>Informe seus dados e continue a conversa pelo WhatsApp.</p><label>Seu nome<input value={name} onChange={event => setName(event.target.value)} required autoComplete="name"/></label><label>Sua cidade<input value={city} onChange={event => setCity(event.target.value)} required/></label><button className="button" type="submit"><MessageCircle size={18}/> Solicitar pelo WhatsApp</button></form> }
function StaticPage({ type }: { type: 'about' | 'contact' }) { const about = type === 'about'; usePageMeta(about ? 'A Fábrica de Púlpitos para Igreja | Altar Púlpitos' : 'Contato e Orçamento de Púlpitos | Altar Púlpitos', about ? 'Conheça a Altar Púlpitos, fábrica de púlpitos para igreja. Atendimento direto e envio para todo o Brasil.' : 'Entre em contato com a Altar Púlpitos pelo WhatsApp para tirar dúvidas e solicitar orçamento de púlpitos para igreja.'); return <Layout><section className="page-hero text-page"><p className="eyebrow">{about ? 'A FÁBRICA' : 'CONTATO E ORÇAMENTO'}</p><h1>{about ? 'Púlpitos feitos para servir à sua igreja.' : 'Vamos encontrar o púlpito ideal para a sua igreja?'}</h1><p>{about ? 'A Altar Púlpitos produz modelos para igrejas que buscam presença, funcionalidade e cuidado na composição do altar.' : 'Fale com nossa equipe pelo WhatsApp, tire suas dúvidas e solicite um orçamento para a sua cidade.'}</p>{about ? <><h2>Atendimento direto de quem fabrica</h2><p>Do modelo escolhido à orientação para entrega, nosso foco é tornar sua compra simples e segura.</p></> : <a className="button" href={`https://wa.me/${whatsapp}`} target="_blank" rel="noreferrer"><MessageCircle size={18}/> Falar pelo WhatsApp</a>}</section></Layout> }
export function App() { return <Routes><Route path="/" element={<Home/>}/><Route path="/catalogo" element={<Catalog/>}/><Route path="/catalogo/:slug" element={<ProductDetail/>}/><Route path="/sobre" element={<StaticPage type="about"/>}/><Route path="/contato" element={<StaticPage type="contact"/>}/><Route path="/admin/*" element={<Admin/>}/><Route path="*" element={<Home/>}/></Routes> }
