import { ArrowRight, Check, ChevronDown, ChevronRight, Factory, Gem, Menu, MessageCircle, Ruler, ShieldCheck, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import type { FormEvent } from 'react';
import { Link, NavLink, Route, Routes, useParams } from 'react-router-dom';
import { api } from './api';
import type { Category, Product } from './types';
import { Admin } from './Admin';
import { makeWhatsAppUrl } from './whatsapp';
import brandLogo from './assets/logo-altar-pulpitos.png';
import pulpitoCobreImage from './assets/pulpito-cobre-igreja.png';
import pulpitoDouradoImage from './assets/pulpito-dourado-igreja.png';
import pulpitoDuploPrataImage from './assets/pulpito-duplo-prata-igreja.png';
import pulpitoPrataImage from './assets/pulpito-prata-igreja.png';
import pulpitoTriploPrataImage from './assets/pulpito-triplo-prata-igreja.png';
import pulpitoPretoImage from './assets/pulpito-preto-igreja.png';
import pulpitoTriploMarromImage from './assets/pulpito-triplo-marrom-igreja.png';

const whatsapp = import.meta.env.VITE_WHATSAPP_NUMBER ?? '5511999999999';
const pulpitosCategory: Category = { id: 'pulpitos', name: 'Púlpitos', slug: 'pulpitos' };
const makeProduct = (name: string, slug: string, description: string, dimensions: string, image: string, sortOrder: number): Product => ({ id: slug, name, slug, description, dimensions, isPublished: true, sortOrder, categoryId: 'pulpitos', category: pulpitosCategory, images: [{ id: `${slug}-igreja`, url: image, alt: `${name} instalado em ambiente de igreja`, sortOrder: 0 }] });
const catalogFallback: Product[] = [
  makeProduct('Púlpito Cobre', 'pulpito-cobre', 'Púlpito em acabamento cobre com tampo de vidro e mesa lateral coordenada.', 'Medidas sob consulta', pulpitoCobreImage, 1),
  makeProduct('Púlpito Dourado', 'pulpito-dourado', 'Púlpito em acabamento dourado com tampo de vidro e mesa lateral coordenada.', 'Medidas sob consulta', pulpitoDouradoImage, 2),
  makeProduct('Púlpito Duplo Prata', 'pulpito-duplo-prata', 'Púlpito com duas colunas em acabamento prata e porta copo/microfone integrado.', '115 × 70 × 40 cm', pulpitoDuploPrataImage, 3),
  makeProduct('Púlpito Prata', 'pulpito-prata', 'Púlpito prata com tampo de vidro e mesa lateral circular.', 'Púlpito: 115 × 70 × 40 cm · Mesa: 72 cm de altura e tampo de 45 cm', pulpitoPrataImage, 4),
  makeProduct('Púlpito Triplo Prata', 'pulpito-triplo-prata', 'Púlpito de três colunas em acabamento prata, com mesa lateral coordenada.', 'Medidas sob consulta', pulpitoTriploPrataImage, 5),
  makeProduct('Púlpito Preto', 'pulpito-preto', 'Púlpito em acabamento preto com vidro fumê e mesa lateral.', 'Medidas sob consulta', pulpitoPretoImage, 6),
  makeProduct('Púlpito Triplo Marrom', 'pulpito-triplo-marrom', 'Púlpito de três colunas em acabamento marrom, com mesa lateral coordenada.', 'Medidas sob consulta', pulpitoTriploMarromImage, 7),
];

function Header() { const [open, setOpen] = useState(false); return <header className="header"><Link to="/" className="brand" aria-label="Altar Púlpitos, página inicial"><img src={brandLogo} alt="Altar Púlpitos"/></Link><button className="menu-button" onClick={() => setOpen(!open)} aria-label={open ? 'Fechar menu' : 'Abrir menu'}>{open ? <X /> : <Menu />}</button><nav className={open ? 'nav open' : 'nav'} onClick={() => setOpen(false)}><NavLink to="/catalogo">Púlpitos</NavLink><NavLink to="/sobre">A fábrica</NavLink><NavLink to="/contato">Contato</NavLink><Link className="button button-small" to="/catalogo">Pedir orçamento</Link></nav></header> }
function Footer() { return <footer><div><img className="footer-logo" src={brandLogo} alt="Altar Púlpitos"/><p>Púlpitos direto da fábrica para igrejas em todo o Brasil.</p></div><div><strong>Atendimento</strong><p>Segunda a sexta, 8h às 18h</p></div><p>© {new Date().getFullYear()} Altar Púlpitos</p></footer> }
function Layout({ children }: { children: React.ReactNode }) { return <><Header/><main>{children}</main><Footer/></> }
function ProductImage({ product }: { product: Product }) { return product.images[0] ? <img src={product.images[0].url} alt={product.images[0].alt || product.name} loading="lazy"/> : <div className="product-placeholder" aria-label={`Imagem indisponível de ${product.name}`}><span>AP</span></div> }
function Home() { const [products, setProducts] = useState<Product[]>([]); useEffect(() => { api.products().then(items => setProducts(items.length ? items : catalogFallback)).catch(() => setProducts(catalogFallback)); }, []); return <Layout>
  <section className="hero hero-new"><div className="hero-copy"><p className="eyebrow">PÚLPITOS DIRETO DA FÁBRICA</p><h1>Presença, elegância e propósito no altar.</h1><p className="lead">Púlpitos produzidos para valorizar cada ministração. Escolha seu modelo e receba atendimento direto de quem fabrica.</p><div className="hero-actions"><Link className="button" to="/catalogo">Ver modelos <ArrowRight size={18}/></Link><a className="button button-outline" href={`https://wa.me/${whatsapp}`} target="_blank" rel="noreferrer"><MessageCircle size={18}/> Falar com especialista</a></div><div className="hero-badges"><span><Check size={16}/> Fabricação própria</span><span><Check size={16}/> Envio para todo Brasil</span></div></div><div className="hero-brand-card"><img src={pulpitoTriploMarromImage} alt="Púlpito Triplo Marrom em ambiente de igreja"/><div className="brand-card-line"/><p>Projetado para<br/><strong>servir com excelência.</strong></p></div></section>
  <section className="trust-bar"><p>Quem escolhe a Altar Púlpitos recebe</p><span>•</span><strong>Qualidade de fábrica</strong><span>•</span><strong>Atendimento próximo</strong><span>•</span><strong>Acabamento refinado</strong></section>
  <section className="section benefits"><div className="section-intro"><p className="eyebrow">FEITO PARA SUA IGREJA</p><h2>Mais que um móvel. Um ponto de referência para a sua mensagem.</h2></div><div className="benefit-grid"><article><Factory size={30}/><h3>Da fábrica para o altar</h3><p>Sem intermediários: você conversa com quem entende de cada etapa da produção.</p></article><article><Gem size={30}/><h3>Acabamento que permanece</h3><p>Materiais selecionados e atenção aos detalhes para uma peça bonita por muitos anos.</p></article><article><ShieldCheck size={30}/><h3>Compra com segurança</h3><p>Atendimento claro, orçamento personalizado e acompanhamento até a entrega.</p></article></div></section>
  <section className="catalog-preview"><div className="section section-heading-block"><p className="eyebrow">MODELOS EM DESTAQUE</p><h2>Encontre o púlpito que combina com o seu espaço.</h2><p>Linhas clássicas e contemporâneas para diferentes estilos de igreja.</p><Link className="text-link" to="/catalogo">Explorar todos os modelos <ArrowRight size={18}/></Link></div><div className="section"><ProductGrid products={products.slice(0, 6)}/></div></section>
  <section className="process section"><div className="process-copy"><p className="eyebrow">COMO FUNCIONA</p><h2>Seu púlpito em 3 passos simples.</h2><p>Um atendimento leve, transparente e focado no que sua igreja precisa.</p><Link className="button" to="/contato">Começar meu orçamento <ArrowRight size={18}/></Link></div><ol><li><b>01</b><div><h3>Escolha o modelo</h3><p>Veja o catálogo e encontre o estilo ideal.</p></div></li><li><b>02</b><div><h3>Peça seu orçamento</h3><p>Fale pelo WhatsApp e informe sua cidade.</p></div></li><li><b>03</b><div><h3>Receba com tranquilidade</h3><p>Nossa equipe orienta você até a entrega.</p></div></li></ol></section>
  <section className="testimony"><div className="quote-mark">“</div><blockquote>Nosso compromisso é entregar uma peça que represente a importância do altar e faça sentido para a realidade da sua igreja.</blockquote><p>ALtar Púlpitos <span>•</span> Direto da fábrica</p></section>
  <section className="section faq"><div><p className="eyebrow">DÚVIDAS FREQUENTES</p><h2>Antes de pedir seu orçamento</h2><p>Se ainda restar alguma dúvida, nossa equipe está pronta para ajudar pelo WhatsApp.</p></div><div className="faq-list"><details open><summary>Vocês enviam para todo o Brasil?<ChevronDown size={18}/></summary><p>Sim. Informe sua cidade no atendimento para confirmarmos as opções de envio para sua região.</p></details><details><summary>Como solicito um orçamento?<ChevronDown size={18}/></summary><p>Escolha um modelo no catálogo e preencha seu nome e cidade. Você será direcionado ao WhatsApp com a mensagem pronta.</p></details><details><summary>Posso tirar dúvidas antes de comprar?<ChevronDown size={18}/></summary><p>Claro. Nosso atendimento é direto pelo WhatsApp para orientar você sobre modelos e entrega.</p></details></div></section>
  <section className="final-cta"><div><p className="eyebrow">PRONTO PARA COMEÇAR?</p><h2>Leve mais presença para o seu altar.</h2><p>Conheça os modelos disponíveis ou converse agora com nossa equipe.</p><div className="hero-actions"><Link className="button" to="/catalogo">Conhecer púlpitos <ArrowRight size={18}/></Link><a className="button button-outline-light" href={`https://wa.me/${whatsapp}`} target="_blank" rel="noreferrer">Chamar no WhatsApp</a></div></div></section>
</Layout> }
function ProductGrid({ products }: { products: Product[] }) { if (!products.length) return <p className="empty">O catálogo está sendo preparado. Volte em breve.</p>; return <div className="product-grid">{products.map(product => <article className="product-card" key={product.id}><Link to={`/catalogo/${product.slug}`}><ProductImage product={product}/><div><p>{product.category.name}</p><h3>{product.name}</h3><span>Ver detalhes <ArrowRight size={16}/></span></div></Link></article>)}</div> }
function Catalog() { const [products, setProducts] = useState<Product[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [active, setActive] = useState(''); useEffect(() => { api.categories().then(items => setCategories(items.length ? items : [pulpitosCategory])).catch(() => setCategories([pulpitosCategory])); }, []); useEffect(() => { api.products(active || undefined).then(items => setProducts(items.length ? items : catalogFallback)).catch(() => setProducts(catalogFallback)); }, [active]); return <Layout><section className="page-hero"><p className="eyebrow">Catálogo</p><h1>Encontre a peça para seu momento.</h1><p>Conheça os modelos disponíveis e solicite um orçamento personalizado.</p></section><section className="section catalog"><div className="filters"><button className={!active ? 'active' : ''} onClick={() => setActive('')}>Todos</button>{categories.map(category => <button className={active === category.slug ? 'active' : ''} onClick={() => setActive(category.slug)} key={category.id}>{category.name}</button>)}</div><ProductGrid products={products}/></section></Layout> }
function ProductDetail() { const { slug = '' } = useParams(); const [product, setProduct] = useState<Product | null>(null); const [error, setError] = useState(''); useEffect(() => { api.product(slug).then(setProduct).catch(() => { const fallback = catalogFallback.find(item => item.slug === slug); if (fallback) setProduct(fallback); else setError('Produto não encontrado.'); }); }, [slug]); if (error) return <Layout><section className="section"><h1>{error}</h1><Link to="/catalogo">Voltar ao catálogo</Link></section></Layout>; if (!product) return <Layout><section className="section">Carregando produto…</section></Layout>; return <Layout><section className="detail section"><div className="detail-image"><ProductImage product={product}/></div><div><Link className="back" to="/catalogo">← Catálogo</Link><p className="eyebrow">{product.category.name}</p><h1>{product.name}</h1><p className="detail-description">{product.description}</p><p className="dimensions"><Ruler size={18}/><strong>Medidas:</strong> {product.dimensions}</p><QuoteForm product={product.name}/></div></section></Layout> }
function QuoteForm({ product }: { product: string }) { const [name, setName] = useState(''); const [city, setCity] = useState(''); const submit = (event: FormEvent) => { event.preventDefault(); window.open(makeWhatsAppUrl(product, name, city), '_blank', 'noopener,noreferrer'); }; return <form className="quote-form" onSubmit={submit}><h2>Solicite um orçamento</h2><label>Seu nome<input value={name} onChange={event => setName(event.target.value)} required autoComplete="name"/></label><label>Sua cidade<input value={city} onChange={event => setCity(event.target.value)} required/></label><button className="button" type="submit"><MessageCircle size={18}/> Continuar no WhatsApp</button></form> }
function StaticPage({ type }: { type: 'about' | 'contact' }) { const about = type === 'about'; return <Layout><section className="page-hero text-page"><p className="eyebrow">{about ? 'Sobre nós' : 'Contato'}</p><h1>{about ? 'Propósito em cada acabamento.' : 'Vamos conversar?'}</h1><p>{about ? 'Produzimos peças que unem presença, funcionalidade e cuidado para compor espaços de culto.' : 'Conte-nos o que sua igreja precisa. Nossa equipe retornará pelo WhatsApp.'}</p>{about ? <><h2>Um trabalho feito com atenção</h2><p>Do desenho à entrega, valorizamos materiais, proporções e detalhes que tornam cada peça especial.</p></> : <a className="button" href={`https://wa.me/${whatsapp}`} target="_blank" rel="noreferrer"><MessageCircle size={18}/> Falar pelo WhatsApp</a>}</section></Layout> }
export function App() { return <Routes><Route path="/" element={<Home/>}/><Route path="/catalogo" element={<Catalog/>}/><Route path="/catalogo/:slug" element={<ProductDetail/>}/><Route path="/sobre" element={<StaticPage type="about"/>}/><Route path="/contato" element={<StaticPage type="contact"/>}/><Route path="/admin/*" element={<Admin/>}/><Route path="*" element={<Home/>}/></Routes> }
